name: Test Email

on:
  workflow_dispatch:
  schedule:
    # Runs at 1 PM UTC (5 AM California Time)
    - cron: '0 13 * * *'

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Send Email
        uses: hilarion5/send-mail@v1
        with:
          smtp-server: smtp.office365.com  # Example for Outlook
          smtp-port: 587
          smtp-secure: true
          from-email: hefnerjoseph87@gmail.com
          to-email: hefnerjoseph87@gmail.com
          username: hefnerjoseph87
          password: "!Excalibur11"
          subject: Test Email
          body: This is a test email sent from GitHub Actions.
          html: |
            <h1>This is a test email</h1>
            <p>Test Paragraph</p>
